name: deploying docker image of testing rizzume

on:
  push:
    branches: main

concurrency: ${{ github.job }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: display git version for debugging purposes
      run: git --version

    - name: deploy to vps
      env:
        VPS: ${{ secrets.VPS }}
        REPO: ${{ github.event.repository.name }}
      run: |
        set -e
        git config --global user.email github-actions[bot]@users.noreply.github.com
        git config --global user.name github-actions[bot]
        echo "Removing existing directory..."
        rm -rf $REPO || true
        echo "cloning repo"
        git clone https://mariooohzc:$VPS@huggingface.co/spaces/mariooohzc/$REPO $REPO
        cd $REPO
        echo "pulling latest changes"
        git pull origin main
        echo "copying dockerfile"
        cp ../Dockerfile .
        git add Dockerfile
        echo "commiting changes"
        git commit --amend -m"$(git show -s --format=%s)"
        echo "pushing changes"
        git push --force-with=lease


