name: deploying docker image of testing rizzume

on:
  push:
    branches: main

jobs:
  deployment:
    on:
      workflow_call:
        secrets:
          token:
            required: true

    jobs:
      deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repoository
          uses: actions/checkout@v4

        - name: deploy to vps
          env:
            VPS: ${{ secrets.vps }}
            REPO: ${{ github.event.repository.name }}
          run: |
            git config user.name "$(git log -n 1 --pretty=format:%an)"
            git config user.email "$(git log -n 1 --pretty=format:%ae)"
            git clone https://mariooohzc:$VPS@huggingface.co/spaces/mariooohzc/$REPO
            pushd $REPO
            cp ../Dockerfile .
            git add Dockerfile
            git commit --ammend -m"$(git show -s --format=%s)"
            git push --force-with=lease


